version: "3.7"

services:
  webscribe:
    #build: .
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MY_CHROME_DRIVER_VERSION: ${MY_CHROME_DRIVER_VERSION:-118.0.5993.70}
    image: amazonlinux2023/webscribe_prod:latest
    container_name: prod_amzlx2023
    privileged: true
    restart: always
    #user: 1000:1000
    volumes:
      - type: bind
        source: ./web-reserve-search
        target: /web-reserve-search
      - type: bind
        source: /root/.aws
        target: /root/.aws
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
      - type: bind
        source: /root/.gitconfig
        target: /root/.gitconfig
    # install cron job schedule for root : このコマンドを実行して終了してしまうからコメントアウトした
    # command: crontab -u root /web-reserve-search/server/cron.d/root.cron
