services:
  webscribe:
    #build: .
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHROME_VERSION: ${CHROME_VERSION:-135.0.7049.114}
        CHROME_DRIVER_VERSION: ${CHROME_DRIVER_VERSION:-135.0.7049.114}
        TARGET_DOWNLOAD_URL: ${TARGET_DOWNLOAD_URL:-}
        CHROMEDRIVER_DOWNLOAD_URL: ${CHROMEDRIVER_DOWNLOAD_URL:-}
        PYTHON3_VERSION: ${PYTHON3_VERSION:-3.12.10}
        WORK_DIR: ${WORK_DIR}
    image: amazonlinux2023/webscribe_prod2025:latest
    container_name: prod_amzlx2025
    privileged: true
    restart: always
    # user: 1000:1000
    volumes:
      - type: bind
        source: ../
        target: /web-reserve-search
      - type: bind
        source: /root/.aws
        target: /root/.aws
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
      - type: bind
        source: /root/.gitconfig
        target: /root/.gitconfig
    # install cron job schedule for root : このコマンドを実行して終了してしまうからコメントアウトした
    # command: crontab -u root /web-reserve-search/server/cron.d/root.cron
